// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrL5uW3Jc-5WOfOQ4Tz86tnR4_OZ1B5Mc',
    appId: '1:1085199802055:web:1a28cbd91a6b0de798a8e2',
    messagingSenderId: '1085199802055',
    projectId: 'flutter-test-44739',
    authDomain: 'flutter-test-44739.firebaseapp.com',
    storageBucket: 'flutter-test-44739.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPUowqKSwiFsagbh1J20eTUIZy_KVzZRo',
    appId: '1:1085199802055:android:49061d69284511ea98a8e2',
    messagingSenderId: '1085199802055',
    projectId: 'flutter-test-44739',
    storageBucket: 'flutter-test-44739.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrL5uW3Jc-5WOfOQ4Tz86tnR4_OZ1B5Mc',
    appId: '1:1085199802055:web:e177dc60b4448f1498a8e2',
    messagingSenderId: '1085199802055',
    projectId: 'flutter-test-44739',
    authDomain: 'flutter-test-44739.firebaseapp.com',
    storageBucket: 'flutter-test-44739.appspot.com',
  );
}
